[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>0.12"]

[tool]
[tool.poetry]
authors = ["Somebody <you@example.com>"]
description = ""
name = "lab1"
version = "0.1.0"
[tool.poetry.dependencies]
requests = "^2.26"
python = "^3.10"
[tool.poetry.dev-dependencies]
